### ISSUE TITLE
Definir proyecto

### ISSUE THREAD

**Issue by Quirrod** [DJANG-OS/DJANG-OS#1]
Se buscara como equipo en SICOES algún proyecto a realizar
Esto sin usar los proyectos listados de la plataforma virtual

### Recursos del proyecto:
https://www.infosicoes.com/adquisicion-de-software-uso-manejo-control-y-administracion-de-informacion-en-el-zoologico-municipal-para-el-registro-de-animales-version-multiusuario-tipo-de-licencia-fu-lct462877.html

**Comment by Quirrod** [comment]
https://www.infosicoes.com/adquisicion-de-software-uso-manejo-control-y-administracion-de-informacion-en-el-zoologico-municipal-para-el-registro-de-animales-version-multiusuario-tipo-de-licencia-fu-lct462877.html

**Comment by FabianSegurondo** [comment]
### User story

- **Como (descripción del usuario)**: Todo el equipo.
- **Quiero (funcionalidad)**:  Encontrar, seleccionar y definir un proyecto de SICOES
- **Para que (beneficio)**: Aprender buenas practicas de ingeniería de software y presentación de proyectos.

### Criterios de aceptación
- **Dado en (como empieza la tarea)**:  Inicio del proyecto.
- **Cuando (acciones tomadas)**: Buscar y escoger proyecto de la pagina de SICOES.
- **Entonces (resultados de las acciones)**: Tendremos el proyecto definido .
