### ISSUE TITLE
Descripción del proyecto 

### ISSUE THREAD

**Issue by Quirrod** [DJANG-OS/DJANG-OS#10]
Llenar la wiki con la informacion general del proyecto

**Comment by FabianSegurondo** [comment]
### User story

- **Como (descripción del usuario)**: Todo el equipo.
- **Quiero (funcionalidad)**: Establecer una clara introducción, objetivos y requerimientos para el proyecto.
- **Para que (beneficio)**: Establecer todo el marco de trabajo bajo lineamientos claros y objetivos.

### Criterios de aceptación
- **Dado en (como empieza la tarea)**: Inicio del desarrollo del proyecto ya escogido.
- **Cuando (acciones tomadas)**: Estructuración de la introducción del proyecto, fijado de objetivo y metas, detalle de requerimientos y la identificación de los usuarios.
- **Entonces (resultados de las acciones)**: Se identifica de manera muy clara en que consiste el proyecto
