### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by Quirrod** [DJANG-OS/DJANG-OS#11]
Diagramas de caso de uso que representan las acciones que tendrá el programa.
Requerimientos:
- Se necesitan definir las acciones que se harán en el programa.
-  Se necesita una visión del funcionamiento del programa.

**Comment by LaBalaElmo** [comment]
User story
Como (descripción del usuario): Obteniendo las funcionalidades del proyecto.
Quiero (funcionalidad): Mostrar de mejor manera las funcionalidades.
Para que (beneficio): Un mejor entendimiento del proyecto

Criterios de aceptación
Dado en (como empieza la tarea): definir las funcionalidades
Cuando (acciones tomadas): analizando todo el proyecto.
Entonces (resultados de las acciones): Una mejor visión del proyecto.
