### ISSUE TITLE
Realizar la wiki

### ISSUE THREAD

**Issue by Quirrod** [DJANG-OS/DJANG-OS#2]
Descripciones y partes del proyecto que ayudaran a visualizar de mejor forma  todo el proyecto y su funcionamiento.

**Comment by FabianSegurondo** [comment]
### User story

- **Como (descripción del usuario)**: Todo el equipo
- **Quiero (funcionalidad)**: Trabajar en todo el desarrollo de la pagina wiki del proyecto.
- **Para que (beneficio)**: Tener la guía de documentación del proyecto.

### Criterios de aceptación
- **Dado en (como empieza la tarea)**: Establecer la pagina wiki para guia del proyecto.
- **Cuando (acciones tomadas)**: Trabajar en el GitHub con las secciones y contenido para el proyecto.
- **Entonces (resultados de las acciones)**: Desarrollo concluido de la documentación inicial de la wiki
