### ISSUE TITLE
Realizar los Mockups

### ISSUE THREAD

**Issue by Quirrod** [DJANG-OS/DJANG-OS#3]
Se realizara los mockups en Figma
Esto para tener una base del proyecto.

**Comment by FabianSegurondo** [comment]
### User story

- **Como en Figma**:
- **Quiero realizar Mockups**:
- **Para tener una idea base del projecto**:

### Criterios de aceptación
- **Dado en Figma**:
- **Cuando Se realicen todas las pantallas**:
- **Entonces Mockups hechos**:
