### ISSUE TITLE
Estilizacion de pantallas

### ISSUE THREAD

**Issue by Quirrod** [DJANG-OS/DJANG-OS#46]
Se realizara una mejor presentaion de las pantalla, para que sea mas amable a la vista del usuario

**Comment by FabianSegurondo** [comment]
### User story
#Como (descripción del usuario): Operador del sistema
#Quiero (funcionalidad): establecer la funcionalidad y navegacion de pantallas.
#Para que (beneficio): la pagina funcione correctamente.
### Criterios de aceptación
#Dado en (como empieza la tarea): elaboracion del frontend.
#Cuando (acciones tomadas): desarrollo de pagina funcionales con angular12.
#Entonces (resultados de las acciones): La paginas y pantallas funcionan para la navegacion.
