### ISSUE TITLE
arquitectura de software

### ISSUE THREAD

**Issue by Quirrod** [DJANG-OS/DJANG-OS#9]
Realizar el diagrama general de la arquitectura, el diagrama y tecnologías de Front-end y el diagrama y tecnología de back-end.

**Comment by FabianSegurondo** [comment]
### User story

- **Como (descripción del usuario)**: EL equipo
- **Quiero (funcionalidad)**: Definir y presentar la arquitectura del software a emplear en el proyecto.
- **Para que (beneficio)**: Se establezca el marco de trabajo con las capas identificadas correctamente y con las tecnologías escogidas.

### Criterios de aceptación
- **Dado en (como empieza la tarea)**: Búsqueda de tecnologías y herramientas para la elaboración de los diagramas de front-end y back-end.
- **Cuando (acciones tomadas)**: detalle y elaboración de conceptos en diagramas sobre la representación de cada tecnología empleada para cada capa.
- **Entonces (resultados de las acciones)**: La arquitectura del proyecto se encuentra estructurada y establecida para empezar con el marco de trabajo.
